### ISSUE TITLE
wechatFerry无法启动微信

### ISSUE THREAD

**Issue by xiaowu-ai-crypto** [Saroth/docker_wechat#1]
您好呀，请问我运行luanch.sh的时候输出环境为64核心，仅支持32核心的错误。 请问这个需要怎么解决。以下图片是我运行错误，以及物理机环境。。
![WechatIMG61](https://github.com/user-attachments/assets/22eba59e-db34-4ae5-a729-9ac33d015943)
![WX20240807-171710](https://github.com/user-attachments/assets/d76daf7c-fe81-4436-938e-9f3a3caf7ef6)

**Comment by Saroth** [comment]
您这情况，可能是ntdll库最多仅支持32核。
可以在docker run加上选项：--cpus=32，试试看能否解决

**Comment by xiaowu-ai-crypto** [comment]
上面那个64核心的机器，限制使用核心0-31无论无何都没有用。限制的是使用0-31，但是并不是在构建wine的时候只能发现32个核。就是在容器内lscpu输出的依然是64。所以先不管上面那个呢，下面我换了一台普通的pc物理机器，这次显示wine内的权限问题，这个我更没见过这个错误。
![WechatIMG64](https://github.com/user-attachments/assets/c4576b40-6a84-43eb-896c-d18c3192a422)
![WX20240808-105002](https://github.com/user-attachments/assets/6ef8db3e-6adc-4f8c-9466-ba5e2414af37)

**Comment by Saroth** [comment]
在不同环境下，Wine确实有各种各样的问题，我也没找到解决方法。

此前在几个平台有部署过，结论是可能和内核版本有关：
* 三台配置一样的云服务器，系统CentOS 7，kernel 3.10.0差几个小版本。都启动失败，而且报错不一样。
* 一台十几年前的老旧物理机，装了新系统Fedora Server 39，kernel 6.9.5。启动成功。
* 本机VMWare里，系统Fedora WorkStations 39，kernel 6.9.5。启动成功。

所以，有条件的话建议用较新的发行版试试

**Comment by M-a-s-a-t-o** [comment]
v39.2.4.zip里已经没有wcf.exe文件了

**Comment by Saroth** [comment]
> v39.2.4.zip里已经没有wcf.exe文件了

好的，我稍后更新下配置

**Comment by Saroth** [comment]
已支持WeChatFerry v39.2.x

**Comment by Saroth** [comment]
已支持WeChatFerry v39.2.x
