### ISSUE TITLE
你好，接受消息的18002接口是关闭的

### ISSUE THREAD

**Issue by metttttt** [Saroth/docker_wechat#3]
<img width="378" alt="image" src="https://github.com/user-attachments/assets/9c7dd0e1-90cf-4d85-aab5-38574002ecb0">
但是18001发送消息是成功的

**Comment by Saroth** [comment]
我本地测试正常，无法重现你的故障。
换了最新版本v39.3.3也测试正常

**Comment by dxian0922** [comment]
18002消息端口压根没法用，wcf的版本都试了一下，只能发消息

**Comment by Saroth** [comment]
> 18002消息端口压根没法用，wcf的版本都试了一下，只能发消息

请参考这个[issue](https://github.com/Saroth/docker_wechat/issues/12)
